#index:
#    path: /
#    controller: App\Controller\DefaultController::index

#home:
   #path: /
   #controller: App\Controller\HomeController::index
   
#gite.home:
      #path: /
      #controller: App\Controller\Gite\GiteController::index